### PR TITLE
Unbind command.

### PR DESCRIPTION
**Pull request by deni64k**
Hi!
I have just added unbind command.
Also I committed updating amqp dependency and using heredoc_unindent.
I guess you will be interested.

### CODE REVIEW

**Comment by dougbarth** [comment]
Hey, cool. Thanks.

When running all the commands, I'm getting the following warning.

```
warning: margin of the first line differs from minimum margin
```

It looks like the blank lines in the banners are throwing off that gem. Can you fix that up?

**Comment by deni64k** [comment]
Okay, i'll fix it.

**Comment by deni64k** [comment]
I have just rebased master and squashed fixing commits.

**Comment by deni64k** [comment]
Sorry, missed button. :)

**Pull request merged**
