### PR TITLE
Please use newer dependencies

### PR DESCRIPTION
**Pull request by swills**
Hi,

I'd like to add this to FreeBSD ports, but in order to do so, I need it to use newer dependencies. Please pull this change which updates the dependencies.

Thanks,
Steve

### CODE REVIEW

**Comment by dougbarth** [comment]
Hi,

Switching to >= for all the gem dependencies will potentially break these commands as newer incompatible versions of those gems are published. I'd rather keep the dependencies well defined to avoid that. Can you let me know which dependencies were causing you trouble?

Instead of switching all the dependencies to >=, I could see removing the patch level from the ~> expressions so they'll auto upgrade more freely.

**Comment by swills** [comment]
Hi,

I need it to work with facets 2.9.1 and json 1.5.3.

Steve

**Comment by dougbarth** [comment]
Hi,

I pushed a commit that loosens the dependencies of those two gems. Can you give it a try and let me know if that solves your issue? If so, I'll release a new version with those changes.

**Comment by swills** [comment]
Unfortunately, I can't test until the new gem is pushed out since we call "gem install", but from the looks of the change I believe it should be fine.

Thanks,
Steve

**Comment by dougbarth** [comment]
Hi Steve,

I released 0.4.3.

**Comment by swills** [comment]
Thanks! That seems to have done the trick.

For the future, would you consider adding "gem test" support? See http://test.rubygems.org/

Thanks again!
Steve

**Pull request closed without merging**
