### PR TITLE
Feature: amqp-spy

### PR DESCRIPTION
**Pull request by jimeh**
Hey, I wrote a quick stand-alone spy script the other day, but I think it's got a better home in your amqp-utils gem :)

I don't know of a way to figure out the type, durability and auto-delete values of an exchange via the AMQP protocol, hence you have to manually supply those values to the command. Aside from that it's nice and easy to use.

Let me know if there's anything you don't like, or would like changed with the command :)

-jim

### CODE REVIEW

**Comment by dougbarth** [comment]
Hi Jim,

Overall, this command looks great. I'd be glad to merge it in with one slight tweak, which I think you'd prefer as well.

I haven't used exchanges in our application yet. Just so I understand the purpose of this command, by binding this temporary queue to the exchange, you are able to receive a copy of each message published to the exchange. The other bound queues also receive the message, so there is no affect to a running application when using this command to spy on the messages, correct?

Poking around the amp library code, it looks like you can remove the need to specify the exchange properties by passing the name of the exchange to the bind method instead of an exchange instance. I would prefer that the exchange configuration is not required for a command like this.

From amqp-0.6.7/lib/mq/queue.rb
     # A valid exchange name (or reference) must be passed as the first
     # parameter. Both of these are valid:
     #  exch = MQ.direct('foo exchange')
     #  queue = MQ.queue('bar queue')
     #  queue.bind('foo.exchange') # OR
     #  queue.bind(exch)

**Comment by jimeh** [comment]
Yes, you are right. It doesn't disturb the existing queues at all. And if I remember right it shouldn't even be putting much load on RabbitMQ, as it only stores a single copy of any one specific message regardless of how many queues it's routed to. As for other brokers, I'd imagine they store messages the same way.

The exchange binding by name is a great find. The only thing I'd imagine _might_ be a problem is specifying a routing key. I'll play around with it today when I get some free time to see what I can do. Thanks :)

**Comment by jimeh** [comment]
Hey, your proposed change seems to work. I did some initial tests a couple of days ago, but I've been too busy to run it through proper testing. I'll have an updated pull request within a few days for you when I've had a chance to make sure it works in any/all scenarios :)

**Comment by jimeh** [comment]
There we go. Finally found time to make sure it works with all types of exchanges and options :)

Sorry for changes to the gemspec in the commit, GitX didn't actually show it as staged, so I only noticed it after I pushed the commit :P

**Pull request merged**
